set1 = set(["Water", "Fire"])
set2 = set(["Clothes", "Food"])
print("Original sets:")
print(set1)
print(set2)
r1 = set1.difference(set2)
print("\nDifference of set1 - set2:")
print(r1)
r2 = set2.difference(set1)
print("\nDifference of set2 - set1:")
print(r2)
